AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template
Resources:
   Pubserver1:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: "us-east-1a"
      ImageId: "ami-0dc2d3e4c0f9ebd18"
      InstanceType: "t2.micro"
      KeyName: "centoskey"
      SecurityGroupIds:
      - Ref: SSHSG
      - Ref: HTTPSG
      SubnetId: 
        Ref : CSTPUBSUB
      Tags:
      - Key: Name
        Value: CST-PUB-SERVER